### PR TITLE
Fix error handling when sending messages fails

### LINKED ISSUE #149: Refactor InvalidMessageException
The InvalidMessageException currently relies on a Message as container for all information, although it occours when parsing the incoming JSON fails. InvalidMessageException should either only rely on a JSON String or be replaced by a IOException.

### PR DESCRIPTION
**Pull request by bitzl**
When sending outgoing messages fails processing should stop as retrying
might cause situations that are very hard to debug (e.g. messages send
multiple times).

Fixes #149.

### CODE REVIEW

File: framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Engine.java [hunk 1]
```diff
@@ -139,34 +140,51 @@ public void start() {
...
+
+  private void retryOrFail(Message receivedMessage, RuntimeException e) {
+    try {
+      boolean isRejected = messageBroker.reject(receivedMessage);
+      if (isRejected) {
+        processReport.reportReject(receivedMessage, e);
+      } else {
+        processReport.reportFailAfterMaxRetries(receivedMessage, e);
       }
+    } catch (IOException fatalExecption) {
```
Comment (tomzirn) [inline framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Engine.java:174]: NIT: Typo
```suggestion
    } catch (IOException fatalException) {
```
